input CreateSiteInput {
  name: String!
  location: [SiteLocationInput!]!
  orgId: ID!
}

input UpdateSiteInput {
  name: String
  location: [SiteLocationInput]
}

input SiteLocationInput {
  lat: Float!
  lng: Float!
}
